<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
/** @var $block \Webkul\Marketplace\Block\Account\Editprofile */
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$partner = $block->getPersistentData();
if (empty($partner)) {
    $partner=$helper->getSeller();
}
$profile_hint_status = $helper->getProfileHintStatus();
$currencySymbol = $helper->getCurrencySymbol();
$formPostUrl = $block->getUrl(
    'marketplace/account/editProfilePost',
    ["_secure" => $block->getRequest()->isSecure()]
);
$questIcon = $block->getViewFileUrl('Webkul_Marketplace::images/quest.png');
$deleteIcon = $block->getViewFileUrl('Webkul_Marketplace::images/deleteIcon.png');
$countryflag = $block->getViewFileUrl('Webkul_Marketplace::images/country/countryflags/');
?>
<form id='edit-vendor-profile-form' action="<?= $escaper->escapeUrl($formPostUrl) ?>" 
    enctype="multipart/form-data" 
    method="post" data-role="form-profile-validate" 
    data-mage-init='{"validation":{}}'>
    <div class="wk-mp-design">
        <fieldset class="fieldset info wk-mp-fieldset">
            <div data-mage-init='{"formButtonAction": {}}' 
                class="wk-mp-page-title legend" id="wk-mp-editprofile-form">
                <!-- <span><?= /* @noEscape */ __('Edit Profile Information') ?></span> -->
                <button class="button wk-mp-btn sg-orange-button" 
                    title="<?= /* @noEscape */ __('Save Profile') ?>" 
                    type="submit" id="save-btn">
                    <span><span><?= /* @noEscape */ __('Save Profile') ?></span></span>
                </button>
            </div>
            <?= $block->getBlockHtml('seller.formkey')?>
            <?= $block->getBlockHtml('formkey')?>
            <div class="field profile">
                <label><?= /* @noEscape */ __('Contact Number') ?> </label>
                <?php
                if ($profile_hint_status && $helper->getProfileHintCn()) {?>
                    <img src="<?= $escaper->escapeUrl($questIcon); ?>" 
                    class='questimg' 
                    title="<?= $escaper->escapeHtml($helper->getProfileHintCn()) ?>"/>
                    <?php
                } ?>
                <div class="control">
                    <?php
                    $placeholderTxt = __(
                        'Enter Contact Number with country code ex: (123) 456-7890'
                    );
                    ?>
                    <input type="text" id="contact_number" 
                    name="contact_number" 
                    value="<?= $escaper->escapeHtml($partner['contact_number']); ?>" 
                    title="<?= /* @noEscape */ __('Enter Contact Number') ?>" 
                    class="input-text" 
                    placeholder="<?= /* @noEscape */ $placeholderTxt ?>"/>
                </div>
            </div>
            <?php
            if ($helper->getActiveColorPicker()) {?>
                <div class="field profile">
                    <label for="background_width"><?= /* @noEscape */ __('Theme : Background Color') ?> </label>
                    <?php
                    if ($profile_hint_status && $helper->getProfileHintBc()) {?>
                        <img src="<?= $escaper->escapeUrl($questIcon); ?>" 
                        class='questimg' 
                        title="<?= $escaper->escapeHtml($helper->getProfileHintBc()) ?>"/>
                        <?php
                    } ?>
                    <div class="control">
                        <input type="text" id="background_width" 
                        name="background_width" 
                        value="<?= $escaper->escapeHtml($partner['background_width']); ?>" 
                        title="background_width" class="input-text" />
                        <span class="color-pick" 
                        data-role="color-pick" 
                        data-mage-init='{
                            "colorPickerFunction":{
                                "spanBackgroundColor" : "<?= $escaper
                                ->escapeHtml($partner['background_width'])?>",
                                "getActiveColorPickerStatus" : "<?= $escaper
                                ->escapeHtml($helper->getActiveColorPicker())?>",
                                "backgroundWidthSelector" : "#background_width"
                            }
                        }'>
                        </span>
                    </div>
                </div>
                <?php
            } ?>
            <div class="field profile">
                <label for="shoptitle"><?= /* @noEscape */ __('Shop Title') ?></label>
                <?php
                if ($profile_hint_status && $helper->getProfileHintShop()) {?>
                    <img src="<?= $escaper->escapeUrl($questIcon); ?>" 
                    class='questimg' 
                    title="<?= $escaper->escapeHtml($helper->getProfileHintShop()) ?>"/>
                    <?php
                } ?>
                <div class="control">
                    <input type="text" id="shop_title" 
                    name="shop_title" 
                    value="<?= $escaper->escapeHtml($partner['shop_title']); ?>" 
                    title="<?= /* @noEscape */ __('Shop Title')?>" 
                    class="input-text" />
                </div>
            </div>
            <div class="field profile">
                <label for="country_pic"> <?= /* @noEscape */ __('Country') ?> </label>
                <?php
                if ($profile_hint_status && $helper->getProfileHintCountry()) {?>
                    <img src="<?= $escaper->escapeUrl($questIcon); ?>" 
                    class='questimg' 
                    title="<?= $escaper->escapeHtml($helper->getProfileHintCountry()) ?>"/>
                    <?php
                } ?>
                <div class="control">
                    <select name="country_pic" id="country-pic">
                        <option value="" selected="selected" disabled="disabled">
                            <?= /* @noEscape */ __('Select Country')?>
                        </option>
                    <?php foreach ($block->getCountryOptionArray() as $country) {?>
                        <option <?php
                        if ($country['value']!='') {
                            echo ($partner['country_pic']==$country['value']?"selected='selected'":""); ?>
                            value="<?= $escaper->escapeHtml($country['value']); ?>">
                            <?= $escaper->escapeHtml($country['label']);?>
                            </option>
                            <?php
                        }
                    } ?>
                    </select>
                    <img class="country_img_prev" alt="no image" 
                    src="<?= /* @noEscape */ $countryflag."/".strtoupper(
                        $partner['country_pic']==""?"xx":$partner['country_pic']
                    ).".png"; ?>"/>
                </div>
            </div>
            <div class="field profile">
                <label for="logo-pic"> <?= /* @noEscape */ __('Profile picture') ?> </label>
                <?php
                if ($profile_hint_status && $helper->getProfileHintLogo()) {?>
                    <img src="<?= $escaper->escapeUrl($questIcon); ?>" 
                    class='questimg' 
                    title="<?= $escaper->escapeHtml($helper->getProfileHintLogo()) ?>"/>
                    <?php
                } ?>
                <div class="control">
                    <input type="file" id="logo-pic" 
                    alt="no image" name="logo_pic" 
                    title="<?= /* @noEscape */ __('Seller Logo')?>" 
                    class="banner" size="26"/>
                    <div class="logoimage-set">
                        <div class="setimage">
                            <img class="prev-img" 
                            src="<?= $escaper
                            ->escapeUrl($helper->getMediaUrl().'avatar/'.$partner['logo_pic']); ?>"/>
                            <?php
                            $logopic = $partner['logo_pic'];
                            if ($logopic && !$partner['is_default_logo']) {
                                ?>
                                <span class="wk-logoimagedelete" 
                                    title="<?= /* @noEscape */ __('Delete')?>">
                                    <img src="<?= $escaper
                                    ->escapeUrl($deleteIcon); ?>" 
                                    alt="<?= /* @noEscape */ __('Delete Image')?>" 
                                    title="<?= /* @noEscape */ __('Delete Image')?>"/>
                                </span>
                                <?php
                            }?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="field profile">
                <label for="company_description"><?= /* @noEscape */ __('Short Description') ?></label>
                <?php
                if ($profile_hint_status && $helper->getProfileHintDesc()) {?>
                    <img src="<?= $escaper->escapeUrl($questIcon); ?>" 
                    class='questimg' 
                    title="<?= $escaper->escapeHtml($helper->getProfileHintDesc()) ?>"/>
                    <?php
                } ?>
                <div class="control wk-border-box-sizing">
                    <textarea type="text" id="company_description" 
                    name="company_description" title="company_description" 
                    class="input-text compdesi" >
                        <?= /* @noEscape */ $partner['company_description']; ?>
                    </textarea>
                    <?php if ($helper->isWysiwygEnabled()): ?>
                        <script>
                            require([
                                "jquery",
                                "mage/translate",
                                "mage/adminhtml/events",
                                "mage/adminhtml/wysiwyg/tiny_mce/setup"
                            ], function(jQuery) {
                                wysiwygCompanyDescription = new wysiwygSetup("company_description", {
                                    "width" : "100%",
                                    "height" : "200px",
                                    "plugins" : [{"name":"image"}],
                                    "tinymce" : {
                                        "toolbar":"formatselect | bold italic underline | "+
                                        "alignleft aligncenter alignright |" + 
                                        "bullist numlist |"+
                                        "link table charmap","plugins":"advlist "+
                                        "autolink lists link charmap media noneditable table "+
                                        "contextmenu paste code help table",
                                    },
                                    files_browser_window_url: "<?= $escaper
                                    ->escapeUrl($block->getWysiwygUrl());?>"
                                });
                                wysiwygCompanyDescription.setup("exact");
                            });
                        </script>
                    <?php endif; ?>
                </div>
            </div>
        </fieldset>
    </div>
</form>
<?php
$profileUrl = 'marketplace/seller/profile/shop/'.$partner['shop_url'];
$collectionUrl = 'marketplace/seller/collection/shop/'.$partner['shop_url'];
$feedbackUrl = 'marketplace/seller/feedback/shop/'.$partner['shop_url'];
$locationUrl = 'marketplace/seller/location/shop/'.$partner['shop_url'];
$policyUrl = 'marketplace/seller/policy/shop/'.$partner['shop_url'];

if ($helper->getUrlRewrite()) { ?>
    <br><br>
    <?php
    $rewriteUrl = $block->getUrl(
        'marketplace/account/rewriteUrlPost',
        ["_secure" => $block->getRequest()->isSecure()]
    );
    ?>
    <form action="<?= $escaper->escapeUrl($rewriteUrl) ?>" 
        enctype="multipart/form-data" method="post" 
        data-role="form-urlrewrite-validate" 
        data-mage-init='{"validation":{}}'>
        <div class="page-title" style="width:100%;display:inline-block;">
            <h2 style="float:left;">
                <?= /* @noEscape */ __('Manage Your Shop Url') ?>
            </h2>
            <button class="button wk-mp-btn" 
                title="<?= /* @noEscape */ __('Set Your New Shop Url') ?>" 
                type="submit" style="float:right;">
                <span><span><?= /* @noEscape */ __('Save Url') ?></span></span>
            </button>
        </div>
        <?= $block->getBlockHtml('seller.formkey')?>
        <?= $block->getBlockHtml('formkey')?>
        <div class="wk-mp-design">
            <fieldset class="fieldset info wk-mp-fieldset">
                <legend class="legend"><span><?= /* @noEscape */ __('Edit Your Shop Url') ?></span></legend>
                <div class="field">
                    <label><?= /* @noEscape */ __('Profile Page Target Url Path') ?></label>
                    <div class="control">
                        <input type="text" class="input-text" 
                        value="<?= /* @noEscape */ $profileUrl ?>" readonly/>
                    </div>
                </div>
                <div class="field">
                    <label><?= /* @noEscape */ __('Profile Page Request Url Path') ?></label>
                    <div class="control">
                        <input type="text" class="input-text" 
                        name="profile_request_url" id="profile_request_url" 
                        value="<?= /* @noEscape */ $helper->getRewriteUrlPath($profileUrl) ?>"/>
                    </div>
                </div>
                <div class="field">
                    <label><?= /* @noEscape */ __('Collection Page Target Url Path') ?></label>
                    <div class="control">
                        <input type="text" class="input-text" 
                        value="<?= /* @noEscape */ $collectionUrl ?>" readonly/>
                    </div>
                </div>
                <div class="field">
                    <label><?= /* @noEscape */ __('Collection Page Request Url Path') ?></label>
                    <div class="control">
                        <input type="text" class="input-text" 
                        name="collection_request_url" id="collection_request_url" 
                        value="<?= /* @noEscape */ $helper->getRewriteUrlPath($collectionUrl) ?>"/>
                    </div>
                </div>
                <div class="field">
                    <label><?= /* @noEscape */ __('Review Page Target Url Path') ?></label>
                    <div class="control">
                        <input type="text" class="input-text" 
                        value="<?= /* @noEscape */ $feedbackUrl; ?>" readonly/>
                    </div>
                </div>
                <div class="field">
                    <label><?= /* @noEscape */ __('Review Page Request Url Path') ?></label>
                    <div class="control">
                        <input type="text" class="input-text" 
                        name="review_request_url" id="review_request_url" 
                        value="<?= /* @noEscape */ $helper->getRewriteUrlPath($feedbackUrl) ?>"/>
                    </div>
                </div>
                <div class="field">
                    <label><?= /* @noEscape */ __('Location Page Target Url Path') ?></label>
                    <div class="control">
                        <input type="text" class="input-text" 
                        value="<?= /* @noEscape */ $locationUrl; ?>" readonly/>
                    </div>
                </div>
                <div class="field">
                    <label><?= /* @noEscape */ __('Location Page Request Url Path') ?></label>
                    <div class="control">
                        <input type="text" class="input-text" 
                        name="location_request_url" id="location_request_url" 
                        value="<?= /* @noEscape */ $helper->getRewriteUrlPath($locationUrl) ?>"/>
                    </div>
                </div>
                <div class="field">
                    <label><?= /* @noEscape */ __('Privacy Policy Page Request Url Path') ?></label>
                    <div class="control">
                        <input type="text" class="input-text" 
                        name="policy_request_url" id="policy_request_url" 
                        value="<?= /* @noEscape */ $helper->getRewriteUrlPath($policyUrl) ?>"/>
                    </div>
                </div>
            </fieldset>
        </div>
    </form>
    <?php
}
?>
<!-- <br><br> -->
<?= $block->getChildHtml(); ?>
<!-- <div class="field profile wk-profile-links-container">
    <div class="wk-profile-links">
        <a class="btn-primary sg-orange-button" 
        href="<?= /* @noEscape */ $helper->getRewriteUrl($profileUrl); ?>" 
        target="_blank"><?= /* @noEscape */ __('View Profile') ?></a>
    </div>
</div> -->
<?php
$formData = [
    'countryPicSelector' => '#country-pic',
    'countryImgPrevSelector' => '.country_img_prev',
    'countryLatitudeSelector' => '#country-latitude',
    'countryLongitudeSelector' => '#country-longitude',
    'countryImgPrev' => $block->getViewFileUrl("Webkul_Marketplace::images/country/countryflags/"),
    'backgroundWidthSelector' => '#background_width',
    'logoPicSelector' => '#logo-pic',
    'bannerPicSelector' => '#banner-pic',
    'leftButtonSelector' => '.left',
    'buttonsSetLastSelector' => '.buttons-set:last',
    'inputTextSelector' => '.input-text',
    'profileimageSetSpanSelector' => '.profileimage-set span',
    'bannerSelector' => '.wk-banner',
    'bannerDeleteAjaxUrl' => $block->getUrl(
        'marketplace/account/deleteSellerBanner',
        ['_secure' => $block->getRequest()->isSecure()]
    ),
    'setimageSelector' => '.setimage',
    'profileImageDeleteSelector' => '.wk-profileimagedelete img',
    'logoImageSetSpanSelector' => '.logoimage-set span',
    'logoSelector' => '.wk-logo',
    'logoDeleteAjaxUrl' => $block->getUrl(
        'marketplace/account/deleteSellerLogo',
        ['_secure' => $block->getRequest()->isSecure()]
    ),
    'logoImageDeleteSelector' => '.wk-logoimagedelete img'
];
$serializedFormData = $viewModel->getJsonHelper()->jsonEncode($formData);
?>

<script type="text/x-magento-init">
    {
        "*": {
            "editSellerProfile": <?= /* @noEscape */ $serializedFormData; ?>
        }
    }
</script>