<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   OrionAlliance_NewModule
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<img src="<?= $escaper->escapeUrl($block->getSellerStatisticsGraphUrl(true)) ?>" 
alt="<?= /* @noEscape */ __('Top Selling Country'); ?>" 
title="<?= /* @noEscape */ __('Top Selling Country'); ?>" id="wk-location-chart"/>
