<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpAdvancedBookingSystem
 * @author    Webkul Software Private Limited
 * @copyright Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/** @var $block \Webkul\Marketplace\Block\Product\Create */
?>
<?php
$viewModel = $block->getBookingViewModel();
if ($viewModel === null) {
    $viewModel = $block->getLayout()->createBlock(
        \Webkul\MpAdvancedBookingSystem\Block\GetViewModel::class
    )->getBookingViewModel();
}
$helper = $viewModel->getHelper();
$params = $block->getRequest()->getParams();
$languageSeniorityPairs = '[]';
$skillsSeniorityPairs = '[]';

if (!empty($params['booking_type'])) {
    $data = $helper->getAttributeSetAndProductTypeForBooking($params['booking_type']);
    if (!empty($data)
        && $data['set'] == $params['set']
        && $data['type'] == $params['type']
        && (($params['type'] == "virtual" && $data['booking_type'] == "booking")
        || ($params['type'] == "configurable" && $data['booking_type'] == "hotelbooking"))
    ) {
        $allowedBookingTypes = explode(',', $helper->getMpConfigValue('booking_types'));
        if (in_array($params['booking_type'], $allowedBookingTypes)) {
            echo "<input id='product_booking_type_id' name='type' type='hidden' value='{$data['booking_type']}'/>";
            echo "<input id='booking_product_type' name='booking_product_type' type='hidden' value='{$params['booking_type']}'/>";
            echo $block->getChildHtml($params['booking_type'] . '-booking');
        }
    } 
    ?>
    <script type="text/javascript">
        window.senioritiesOptions = <?php echo $block->getLanguageSenioritiesOptions(); ?>;
        window.languagesOptions = <?php echo $block->getLanguagesOptions(); ?>;
        window.languageSeniorityPairs = <?php echo $languageSeniorityPairs; ?>;
        window.skillsOptions = <?php echo $block->getSkillsOptions(); ?>; // Added for skills-seniority
        window.skillSenioritiesOptions =  <?php echo $block->getSkillSenioritiesOptions(); ?>;
        window.skillSeniorityPairs = <?php echo $skillsSeniorityPairs; ?>;
    </script>

    <div class="admin__field field required">
        <label for="language"> <?= /* @noEscape */ __('Language') ?> </label>
        <div class="admin__field-control">
            <div data-bind="scope: 'languageSeniority'">
                <input name="product[language_seniority]" data-bind="value: value" type="hidden"/>
                <div data-bind="template: { name: 'Webkul_MpAdvancedBookingSystem/form/element/language-seniority' }"></div>
            </div>
        </div>
    </div>

    <div class="field profile required">
        <label for="product[country_pic]"> <?= /* @noEscape */ __('Country') ?> </label>
        <div class="control">
            <select name="product[country_pic]" id="country-pic">
                <option value="" selected="selected" disabled="disabled">
                    <?= /* @noEscape */ __('Select Country')?>
                </option>
                <?php foreach ($viewModel->getCountryOptionArray() as $country) {?>
                    <option value="<?= $escaper->escapeHtml($country['value']); ?>">
                        <?= $escaper->escapeHtml($country['label']);?>
                    </option>
                <?php } ?>
            </select>
        </div>
    </div>

    <?php
        $industryExpertiseOptions = $viewModel->getIndustryExpertiseOptions();
        // $selectedOptions = explode(',', $block->getProduct()->getData('industry_expertise')); // Assuming selected options are stored as comma-separated values
        $attributeCode = 'product[industry_expertise]';
        $reactAppConfigs = [
            [
                'attributeCode' => $attributeCode,
                'options' => $industryExpertiseOptions,
                'label' => 'Industry Expertise',
                'selectedOptions' => [],
                'isRequired' => false, // Change if required
            ]
        ];
    ?>
    <div id="<?= /**@noEscape */ $attributeCode; ?>"></div>
    <script type="text/javascript">
        window.reactAppConfigs = <?= json_encode($reactAppConfigs); ?>;
    </script>
    <script type="text/javascript" src="<?= $block->getViewFileUrl('Webkul_MpAdvancedBookingSystem/js/multiselect2.js') ?>"></script>

    <div class="field profile required" style="display: none;">
        <label for="product[industry_expertise]"> <?= /* @noEscape */ __('Industry Expertise') ?> </label>
        <div class="control">
            <select name="product[industry_expertise]" multiple="multiple">
                <option value="" disabled="disabled">
                    <?= /* @noEscape */ __('Select Industry Expertise')?>
                </option>
                <?php foreach ($viewModel->getIndustryExpertiseOptions() as $option) {?>
                    <option value="<?= $escaper->escapeHtml($option['value']); ?>">
                        <?= $escaper->escapeHtml($option['label']);?>
                    </option>
                <?php } ?>
            </select>
        </div>
    </div>

    <div class="admin__field field required">
        <label for="skill"> <?= /* @noEscape */ __('Skill') ?> </label>
        <div class="admin__field-control">
            <div data-bind="scope: 'skillSeniority'"> <!-- Added for skills-seniority -->
                <input name="product[skill_seniority]" data-bind="value: value" type="hidden"/>
                <div data-bind="template: { name: 'Webkul_MpAdvancedBookingSystem/form/element/skill-seniority' }"></div>
            </div>
        </div>
    </div>

    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "languageSeniority": {
                        "component": "Webkul_MpAdvancedBookingSystem/js/form/element/language-seniority"
                    },
                    "skillSeniority": {
                        "component": "Webkul_MpAdvancedBookingSystem/js/form/element/skill-seniority"
                    }
                }
            }
        }
    }
    </script>
<?php 
} elseif (!(empty($params['id'])) && $helper->isBookingProduct($params['id'])) {
    $productId = $params['id'];
    $languageSeniorityPairs = $productId ? json_encode($block->getLanguageSeniorityPairs($productId)) : '[]';
    $skillSeniorityPairs = $productId ? json_encode($block->getSkillSeniorityPairs($productId)) : '[]';

    $currentCountryPic = $block->getCountry($productId);
    $currentIndustryExpertise = explode(',', $block->getIndustryExpertise($productId));

    $helper->enableOptions($productId);
    $helper->checkBookingProduct($productId);

    $product = $helper->getProduct($productId);
    $set = $product->getAttributeSetId();

    $allowedBookingProductTypes = [
        "booking",
        "hotelbooking"
    ];

    $defaultType = $helper->getProductAttributeSetIdByLabel('Default');
    $appointmentType = $helper->getProductAttributeSetIdByLabel('Appointment Booking');
    $rentalType = $helper->getProductAttributeSetIdByLabel('Rental Booking');
    $eventType = $helper->getProductAttributeSetIdByLabel('Event Booking');
    $hotelType = $helper->getProductAttributeSetIdByLabel('Hotel Booking');
    $tableType = $helper->getProductAttributeSetIdByLabel('Table Booking');

    $allowedAttributeSetIds = $helper->getAllowedAttrSetIDs();
    $allowedAttributeSetIds[] = $defaultType;

    $allowedBookingTypes = [
        $defaultType => 'default',
        $appointmentType => 'appointment',
        $rentalType => 'rental',
        $eventType => 'event',
        $hotelType => 'hotel',
        $tableType => 'table'
    ];

    if (in_array($product->getTypeId(), $allowedBookingProductTypes)
        && in_array($set, $allowedAttributeSetIds)
        && array_key_exists($set, $allowedBookingTypes)
    ) {
        $data = $helper->getAttributeSetAndProductTypeForBooking($allowedBookingTypes[$set]);
        if (!empty($data)
            && $data['set'] == $set
            && in_array($allowedBookingTypes[$set], $helper->getAllBookingTypes())
        ) {
            echo "<input id='booking_product_type' name='booking_product_type' type='hidden' value='{$allowedBookingTypes[$set]}'/>";
            echo $block->getChildHtml($allowedBookingTypes[$set] . '-booking');
        }
    }
    ?>

    <script type="text/javascript">
        window.senioritiesOptions = <?php echo $block->getLanguageSenioritiesOptions(); ?>;
        window.languagesOptions = <?php echo $block->getLanguagesOptions(); ?>;
        window.skillsOptions = <?php echo $block->getSkillsOptions(); ?>; // Added for skills-seniority
        window.skillSenioritiesOptions =  <?php echo $block->getSkillSenioritiesOptions(); ?>;
        window.languageSeniorityPairs = <?php echo $languageSeniorityPairs; ?>;
        window.skillSeniorityPairs = <?php echo $skillSeniorityPairs; ?>;
        window.currentCountryPic = "<?php echo $currentCountryPic; ?>";
        window.currentIndustryExpertise = <?php echo json_encode($currentIndustryExpertise); ?>;
        
    </script>

    <?php
        $industryExpertiseOptions = $viewModel->getIndustryExpertiseOptions();
        // $selectedOptions = explode(',', $block->getProduct()->getData('industry_expertise')); // Assuming selected options are stored as comma-separated values
        $selectedOptions = $currentIndustryExpertise;
        $attributeCode = 'product[industry_expertise]';
        $reactAppConfigs = [
            [
                'attributeCode' => $attributeCode,
                'options' => $industryExpertiseOptions,
                'label' => 'Industry Expertise',
                'selectedOptions' => $selectedOptions,
                'isRequired' => false, // Change if required
            ]
        ];
    ?>
    <div id="<?= /**@noEscape */ $attributeCode; ?>"></div>
    <script type="text/javascript">
        window.reactAppConfigs = <?= json_encode($reactAppConfigs); ?>;
    </script>
    <script type="text/javascript" src="<?= $block->getViewFileUrl('Webkul_MpAdvancedBookingSystem/js/multiselect2.js') ?>"></script>


    <div class="admin__field field required">
        <label for="language"> <?= /* @noEscape */ __('Language') ?> </label>
        <div class="admin__field-control">
            <div data-bind="scope: 'languageSeniority'">
                <input name="product[language_seniority]" data-bind="value: value" type="hidden"/>
                <div data-bind="template: { name: 'Webkul_MpAdvancedBookingSystem/form/element/language-seniority' }"></div>
            </div>
        </div>
    </div>

    <div class="admin__field field required">
        <label for="skill"> <?= /* @noEscape */ __('Skill') ?> </label>
        <div class="admin__field-control">
            <div data-bind="scope: 'skillSeniority'"> <!-- Added for skills-seniority -->
                <input name="product[skill_seniority]" data-bind="value: value" type="hidden"/>
                <div data-bind="template: { name: 'Webkul_MpAdvancedBookingSystem/form/element/skill-seniority' }"></div>
            </div>
        </div>
    </div>

    <div class="field profile required">
        <label for="product[country_pic]"> <?= /* @noEscape */ __('Country') ?> </label>
        <div class="control">
            <select name="product[country_pic]" id="country-pic">
                <option value="" disabled="disabled">
                    <?= /* @noEscape */ __('Select Country')?>
                </option>
                <?php foreach ($viewModel->getCountryOptionArray() as $country) {?>
                    <option value="<?= $escaper->escapeHtml($country['value']); ?>" <?= $currentCountryPic == $country['value'] ? 'selected="selected"' : '' ?>>
                        <?= $escaper->escapeHtml($country['label']);?>
                    </option>
                <?php } ?>
            </select>
        </div>
    </div>

    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "languageSeniority": {
                        "component": "Webkul_MpAdvancedBookingSystem/js/form/element/language-seniority"
                    },
                    "skillSeniority": {
                        "component": "Webkul_MpAdvancedBookingSystem/js/form/element/skill-seniority"
                    }
                }
            }
        }
    }
    </script>
    <?php
}
?>

<!-- Add hidden input for language_seniority_pairs -->
<!-- <input type="hidden" name="product[language_seniority]" id="language_seniority" /> -->

<!-- <script type="text/javascript">
    require(['jquery'], function($) {
        $(document).ready(function() {
            // Set the value of the hidden input field with the language seniority pairs
            var languageSeniorityPairs = window.languageSeniorityPairs;
            $('#language_seniority').val(JSON.stringify(languageSeniorityPairs));
        });
    });
</script> -->

<!-- Add hidden input for skill_seniority_pairs -->
<!-- <input type="hidden" name="product[skill_seniority]" id="skill_seniority" /> -->

<!-- <script type="text/javascript">
    require(['jquery'], function($) {
        $(document).ready(function() {
            // Set the value of the hidden input field with the skill seniority pairs
            var skillSeniorityPairs = window.skillSeniorityPairs;
            $('#skill_seniority').val(JSON.stringify(skillSeniorityPairs));
        });
    });
</script> -->