<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$helperOrders = $viewModel->getOrderHelper();
$partner = $block->getProfileDetail();
$currentUrl = $escaper->escapeUrl($block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]));

if ($partner['shop_url']):
    $bannerpic = $partner->getBannerPic()!=''?$partner->getBannerPic():$helper->getProfileBannerImage();
    $bannerpic = $helper->getMediaUrl().'avatar/'.$bannerpic;

    $logo = $partner->getLogoPic()!=''?$partner->getLogoPic():"noimage.png";
    $logo = $helper->getMediaUrl().'avatar/'.$logo;
    $sizeArr = $helper->getImageSize($logo);
    if (!empty($sizeArr) && !empty($sizeArr['width']) && !empty($sizeArr['height'])) {
        $width = $sizeArr['width'];
        $height = $sizeArr['height'];
        $calculatedHeight = 80;
        $calculatedWidth = ($width / $height) * $calculatedHeight;
        $calculatedPercent = ($width / $height) * 2.5;
        if ($calculatedHeight) { ?>
            <style>
                .wk-mp-collection-seller-title-container {
                    padding-left: calc(<?= /* @noEscape */ $calculatedPercent ?>% + 
                    <?= /* @noEscape */ $calculatedWidth ?>px);
                }
            </style>
            <?php
        }
    }
    $shopUrl = $escaper->escapeHtml($partner['shop_url']);
    $shoptitle = $escaper->escapeHtml($partner->getShopTitle());
    if (!$shoptitle) {
        $shoptitle = $shopUrl;
    }
    $sellerId = $partner->getSellerId();
    $locsearch = $escaper->escapeHtml($partner['company_locality']);
    $sellerProductCount = $helper->getSellerProCount($sellerId);
    $flagReasons = $block->getSellerFlagReasons();


    


    if ($helper->getActiveColorPicker()):?>
        <style>
            .marketplace-seller-collection .wk-mp-collection-product-count-container,
            .marketplace-seller-profile .wk-mp-collection-product-count-container,
            .marketplace-seller-feedback .wk-mp-collection-rating-count-container {
                border-bottom-color: <?= $escaper->escapeHtml($partner['background_width']);?>;
            }
        </style>
    <?php endif ?>
    <?php  // starting of the div ?>
    <?php
        // $customer = $block->getCustomer('');
        $customer = $partner->getData('customer_data');
        // $customer = $block->getCustomer2($sellerId);
        $isSeller = TRUE;       

        $reactAppVendorConfig = [
            'title' => $shoptitle,
            'country' => $partner['country_pic'],
            'short_description' => htmlspecialchars($partner->getCompanyDescription(), ENT_QUOTES, 'UTF-8'),
            'short_description_1' => htmlspecialchars($partner['company_description'], ENT_QUOTES, 'UTF-8'),
            // 'short_description_2' => htmlspecialchars($partner->getDescription(), ENT_QUOTES, 'UTF-8'),
            'short_description_3' => $partner['company_description'],
            'shop_url' => $partner['shop_url'],
            'banner_pic' => $partner->getBannerPic(),
            'media_url' => $helper->getMediaUrl(),
            'shop_title' => $partner->getShopTitle(),
            // 'short_description' => $partner->getShortDescription(),
            'seller_rating' => $helper->getSelleRating($partner->getSellerId()),
            'profile_hint_desc' => $helper->getProfileHintDesc(),
            'logo' => $logo
        ];

        $vendorAttributes = $block->getAttributeCollection($isSeller);
        foreach ($vendorAttributes as $vendorAttribute) {
            $attributeCode = $vendorAttribute->getAttributeCode();
            // $options = $vendorAttribute->getSource()->getAllOptions();
            $selectedOptions = $customer->getData($attributeCode);
            $reactAppVendorConfig['attributes'][] = [
                'attributeCode' => $attributeCode,
                // 'options' => $options,
                'selectedOptions' => $selectedOptions
            ];
    ?>
    <?php } ?>
    <div id="vendor-profile"></div>
    <script type="text/javascript">
        window.reactAppVendorConfig = <?= json_encode($reactAppVendorConfig); ?>;
    </script>
    <script type="text/javascript" src="<?= $block->getViewFileUrl('Webkul_MpVendorAttributeManager/js/multiselect.js') ?>"></script>
<?php endif ?>