<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   OrionAlliance_NewModule
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    /** @var \OrionAlliance\NewModule\Block\Adminhtml\Customer\Edit\Tab\Product $block */

    /** @var \OrionAlliance\NewModule\Block\Adminhtml\Customer\Edit\Tab\Grid\Product $blockGrid */
    $blockGrid = $block->getBlockGrid();
    $gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml(); ?>
<script type="text/x-magento-init">
    {
        "*": {
            "OrionAlliance_NewModule/js/seller/assign-products": {
                "selectedProducts": <?= /* @noEscape */ $block->getSellerAssignedProductsJson(); ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
<input type="hidden" name="sellerassignproid" id="in_adminassign_products" data-form-part="customer_form" value="" />
