<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   OrionAlliance_NewModule
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
/** @var $block \OrionAlliance\NewModule\Block\Page\Notofications */
?>
<ul class="wk-mp__action-dropdown-menu wk-mp-dashboard-notifications-menu">
    <?php foreach ($block->getAllNotification() as $notification) {
      /* @noEscape */ echo $block->getNotificationInfo($notification);
    } ?>
    <li>
        <small>
            <a href="<?= $escaper->escapeUrl($block->getUrl('marketplace/account/notification'))?>">
                <?= $escaper->escapeHtml(__("View All"))?>
            </a>
        </small>
    </li>
</ul>
